### ISSUE TITLE
android 测试环境正常，打包后消息发送不出去

### ISSUE THREAD

**Issue by liumingsongning** [leancloud/Realtime-SDK-Flutter#93]
``2020-09-07 09:12:25.955 2184-2618/? D/NetworkController.MobileSignalController(1): 4G level = 5
2020-09-07 09:12:27.389 10040-10040/? W/adbd: timeout expired while flushing socket, closing
2020-09-07 09:12:27.753 15692-15692/? D/i: onMethodCall openClient， args:{r=false, clientId=Tom, signRegistry={sessionOpen=false, conversation=false}}
2020-09-07 09:12:27.753 15692-15692/? D/g: openClient...
2020-09-07 09:12:27.754 15692-15692/? D/k: add request cache. client=Tom, conv=null, request=-65534
2020-09-07 09:12:27.754 15692-15692/? E/e: session error:java.lang.IllegalStateException: Connection Lost
2020-09-07 09:12:27.754 15692-15692/? D/g: enter onOperationCompleted with clientId=Tom, convId=null, requestId=-65534, operation=CLIENT_OPEN
2020-09-07 09:12:27.754 15692-15692/? D/i: client open result: {clientId=Tom}
2020-09-07 09:12:27.755 15692-15722/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: 
    LC.RTM.Exception(
      code: 0,
      essage: java.lang.IllegalStateException: Connection Lost,
      details: Connection Lost,
    )
    #0      _Utilities.call (package:leancloud_official_plugin/src/client.dart:122)
    <asynchronous suspension>
    #1      Client.open (package:leancloud_official_plugin/src/client.dart:454)
    <asynchronous suspension>
    #2      _MyHomePageState._incrementCounter (package:im/main.dart:59)
    <asynchronous suspension>
2020-09-07 09:12:28.527 1942-2078/? I/MiuiNetworkPolicy: bandwidth: 0 KB/s, Max bandwidth: 1826 KB/s
2020-09-07 09:12:28.974 2184-2618/? D/NetworkController.MobileSignalController(1): 4G level = 5
2020-09-07 09:12:29.004 2184-2184/? D/SignalClusterView: updateMobileTypeImage  0
2020-09-07 09:12:29.022 2184-2184/? I/chatty: uid=1000(system) com.android.systemui identical 12 lines
2020-09-07 09:12:29.022 2184-2184/? D/SignalClusterView: updateMobileTypeImage  0
2020-09-07 09:12:29.649 18943-18943/? I/subsystem_ramdump: Usage:./system/bin/subsystem_ramdump [arg1] [arg2] [arg3]

**Comment by zapcannon87** [comment]
@jwfing
